version: '3.8'

services:
  app:
    image: robdetta/brewtrail
    pull_policy: always
    restart: always
    networks:
      - caddy_network

  caddy:
    image: caddy:latest
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
    networks:
      - caddy_network
    depends_on:
      - app

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
