version: '3.8'

services:
  app:
    image: robdetta/brewtrail
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    pull_policy: always
    ports:
      - '8080:8080'
    restart: always
    networks:
      - caddy_network

  caddy:
    image: caddy:latest
    restart: always
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
    networks:
      - caddy_network
    depends_on:
      - app
networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
