version: '3.8'

services:
  app:
    image: robdetta/brewtrail
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt/live:/etc/letsencrypt/live
    depends_on:
      - app
