version: '3.8'

services:
  app:
    image: robdetta/brewtrail
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: databasename
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
