version: '3.8'

services:
  app:
    image: robdetta/brewtrail:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - caddy_network
  caddy:
    image: caddy:latest # Use the latest Caddy image
    ports:
      - '80:80' # Map HTTP port
      - '443:443' # Map HTTPS port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount the Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt
      - caddy_data:/data # Persistent volume for Caddy data
      - caddy_config:/config # Persistent volume for Caddy configuration
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
    networks:
      - caddy_network
    depends_on:
      - app

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
